# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dad8a32d7f676e48092bf6f51ff5e008b49705604e44776eeacfa6459775497fdc68a63bee0a9cfa7c835d3765d8554b8dccc503234d15fc9a08a47baf02185

test:
  secret_key_base: 8e41afa1a3a4f5c6d5b14315500c3f601bafac613f4c5c66cb4154bd34da20b9005b98a38a2c5046b1ef7a5c1385f55a9e5390cabfa77f9e00efb6ba2c9eaa1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
